### ISSUE TITLE
changelog 无法生成

### ISSUE THREAD

**Issue by wongchisum** [TonicFizzRicky/ts-lib-setup-template#4]
修复 changesets/cli 无法生成git changelog 的问题

```
$ pnpm exec changeset
🦋  error PackageJsonMissingNameError: The following package.jsons are missing the "name" field:
🦋  error package.json
🦋  error     at _callee$ (D:\ts-setup-template\node_modules\.pnpm\@manypkg+get-packages@1.1.3\node_modules\@manypkg\get-packages\dist\get-packages.cjs.dev.js:175:19)
🦋  error     at tryCatch (D:\ts-setup-template\node_modules\.pnpm\@babel+runtime@7.20.13\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
🦋  error     at Generator.<anonymous> (D:\ts-setup-template\node_modules\.pnpm\@babel+runtime@7.20.13\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
🦋  error     at Generator.throw (D:\ts-setup-template\node_modules\.pnpm\@babel+runtime@7.20.13\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
🦋  error     at asyncGeneratorStep (D:\ts-setup-template\node_modules\.pnpm\@babel+runtime@7.20.13\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
🦋  error     at _throw (D:\ts-setup-template\node_modules\.pnpm\@babel+runtime@7.20.13\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) {
🦋  error   directories: [ 'package.json' ]
🦋  error }

```

设置 package.json name 字段后，依然无法生成

```
$ pnpm exec changeset
🦋  error Error: Failed to find where HEAD diverged from main. Does main exist?
🦋  error     at getDivergedCommit (D:\ts-setup-template\node_modules\.pnpm\@changesets+git@2.0.0\node_modules\@changesets\git\dist\git.cjs.dev.js:66:11)
🦋  error     at processTicksAndRejections (node:internal/process/task_queues:96:5)
🦋  error     at async getChangedFilesSince (D:\ts-setup-template\node_modules\.pnpm\@changesets+git@2.0.0\node_modules\@changesets\git\dist\git.cjs.dev.js:198:22)
🦋  error     at async Object.getChangedPackagesSinceRef (D:\ts-setup-template\node_modules\.pnpm\@changesets+git@2.0.0\node_modules\@changesets\git\dist\git.cjs.dev.js:239:24)
🦋  error     at async add (D:\ts-setup-template\node_modules\.pnpm\@changesets+cli@2.26.0\node_modules\@changesets\cli\dist\cli.cjs.dev.js:527:29)
🦋  error     at async run$2 (D:\ts-setup-template\node_modules\.pnpm\@changesets+cli@2.26.0\node_modules\@changesets\cli\dist\cli.cjs.dev.js:1330:5)
```

**Comment by wongchisum** [comment]
修正 git commit message 生成的格式
修复 changelog 生成
移除 changeset
